services:
  train:
    image: mental-health-predictor
    working_dir: /app
    command: python src/core/ml/train.py
    volumes:
      - ./src:/app/src
      - ./training_data:/app/training_data
      - ./models:/app/models
    restart: "no"

  redis:
    image: redis:latest
    restart: unless-stopped
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5

  mental-health-predictor-backend:
    image: mental-health-predictor
    container_name: mental-health-predictor-backend
    command: uvicorn main:app --host 0.0.0.0 --reload --proxy-headers
    ports:
      - "8000:8000"
    working_dir: /app/src
    volumes:
      - ./src:/app/src
      - ./training_data:/app/training_data
      - ./models:/app/models
      - ./logs:/var/logs/mental-health-predictor
    env_file:
      - ./environments/.env
    depends_on:
      train:
        condition: service_completed_successfully
      redis:
        condition: service_healthy